export const Menu_List = [
  {
    id: 1,
    title: 'Buttermilk Pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: 'Pancakes are the hero of the breakfast table, and their very taste can even be described as “deeply breakfasty”: eggy, salty, just this side of sweet.',
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: 'Canadian cheese, caramelized onions and All-Canadian sauce on a brioche bun. Served with wavy-cut French fries.',
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'Ice-cream',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: 'abc',
  },
  {
    id: 4,
    title: 'Huevos Rancheros Wraps',
    category: 'breakfast',
    price: 20.99,
    img: './images/brf_00.jpeg',
    desc: 'Organic cage-free eggs, refried beans, cheese and cilantro salsa',
  },
  {
    id: 5,
    title: 'Fried rice',
    category: 'lunch',
    price: 2.29,
    img: './images/item-5.jpeg',
    desc: 'Fried rice is a dish of cooked rice that has been stir-fried in a wok or a frying pan and is usually mixed with other ingredients such as eggs, vegetables, seafood, or meat.',
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'Ice-cream',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: 'abc',
  },
  {
    id: 7,
    title: 'Bacon Overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: 'Carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird',
  },
  {
    id: 8,
    title: 'Pho',
    category: 'lunch',
    price: 2.99,
    img: './images/item-8.jpeg',
    desc: 'Pho is a traditional dish of Vietnam, originating from Hanoi and Nam Dinh, and is considered one of the typical dishes for Vietnamese cuisine.',
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'Ice-cream',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: 'abc',
  },
  {
    id: 10,
    title: 'Jet Pilot Tropical Cocktail',
    category: 'Drink',
    price: 4.65,
    img: './images/drk_00.jpeg',
    desc: 'Fast and courageous. A vigorous blend of heavy bodied rums and zesty juices.',
  },
  {
    id: 11,
    title: 'rose grapefruit tea',
    category: 'drink',
    price: 1.99,
    img: './images/item-11.jpeg',
    desc: 'Inspired by the tropical sea, with the sweet taste of grapes mixed with lotus tea and pineapple jelly, Tra Sen Nho is like a cool breeze blowing away the heat.',
  },
];


export default [
  {
    id: 1,
    title: 'buttermilk pancakes',
    price: 15.99,
    img: './images/item-1.jpeg',
    amount: 1,
  },
  {
    id: 2,
    title: 'american classic',
    price: 12.99,
    img: './images/item-8.jpeg',
    amount: 1,
  },
  {
    id: 3,
    title: 'quarantine buddy',
    price: 16.99,
    img: './images/item-9.jpeg',
    amount: 1,
  },
];
