export const Menu_List = [
  {
    id: 1,
    title: 'Buttermilk Pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: 'Pancakes are the hero of the breakfast table, and their very taste can even be described as “deeply breakfasty”: eggy, salty, just this side of sweet.',
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: 'abc',
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'Ice-cream',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: 'abc',
  },
  {
    id: 4,
    title: 'Huevos Rancheros Wraps',
    category: 'breakfast',
    price: 20.99,
    img: './images/brf_00.jpeg',
    desc: 'Organic cage-free eggs, refried beans, cheese and cilantro salsa',
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: 'abc',
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'Ice-cream',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: 'abc',
  },
  {
    id: 7,
    title: 'Bacon Overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: 'Carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird',
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: 'abc',
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'Ice-cream',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: 'abc',
  },
];


export default [
  {
    id: 1,
    title: 'buttermilk pancakes',
    price: 15.99,
    img: './images/item-1.jpeg',
    amount: 1,
  },
  {
    id: 2,
    title: 'american classic',
    price: 12.99,
    img: './images/item-8.jpeg',
    amount: 1,
  },
  {
    id: 3,
    title: 'quarantine buddy',
    price: 16.99,
    img: './images/item-9.jpeg',
    amount: 1,
  },
];
